server:
  port: 8083
spring:

  application:
    name: mcp-server

  ai:
    mcp:
      server:
        name: swagger-mcp-server
        version: 1.0.0
        type: SYNC
        protocol: STREAMABLE
        capabilities:
          tool: true
          resource: true
          prompt: false
          completion: false
        streamable-http:
          mcp-endpoint: /mcp

  swagger:
    registry:
      services:
        - name: test1
          description: 테스트 서비스1
          openapi-url: http://localhost:8082/v1/api-docs
          aliases:
            - test1
            - 테스트 서비스1
            - 주문 서비스
            - order service
#        - name: test2
#          description: 테스트 서비스2
#          openapi-url: http://localhost:8082/v1/api-docs
#        - name: test3
#          description: 테스트 서비스3
#          openapi-url: http://localhost:8083/v1/api-docs

